name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      placeholder: This will allow...
